name: deno tests and checks

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
      - uses: actions/checkout@v4
      - run: deno task test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
      - uses: actions/checkout@v4
      - run: deno fmt --check
      - run: deno lint
      - run: deno task check
