name: publish tag to jsr.io
on:
  push:
    tags:
      - "0*"
      - "1*"
      - "2*"
      - "3*"
      - "4*"
      - "5*"
      - "6*"
      - "7*"
      - "8*"
      - "9*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2
      - uses: actions/checkout@v4

      - name: Publish package
        run: deno publish
