name: publish tag to jsr.io
on:
  workflow_dispatch:
  push:
    tags:
      - "0*"
      - "1*"
      - "2*"
      - "3*"
      - "4*"
      - "5*"
      - "6*"
      - "7*"
      - "8*"
      - "9*"

jobs:
  publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: 2.9.6

      - name: Validate version tag
        shell: bash
        run: |
          release_number='(0|[1-9][0-9]*)'
          release_identifier='(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)'
          release_pattern="^${release_number}\.${release_number}\.${release_number}(-${release_identifier}(\.${release_identifier})*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$"
          if [[ ! "${GITHUB_REF_NAME}" =~ ${release_pattern} ]]; then
            printf 'Invalid version tag.\n' >&2
            exit 1
          fi

      - run: deno task all

      - name: Publish package
        run: deno publish --allow-slow-types --set-version "${GITHUB_REF_NAME}"
